import React from 'react';
import { StudentData } from '../types/copybook';
import { PARSED_QUESTIONS, EXAM_META } from '../data/copybookData';
import { X, Printer, Download, Award, Send, CheckCircle2 } from 'lucide-react';

interface ParentReportCardModalProps {
  isOpen: boolean;
  onClose: () => void;
  student: StudentData;
}

export const ParentReportCardModal: React.FC<ParentReportCardModalProps> = ({
  isOpen,
  onClose,
  student,
}) => {
  if (!isOpen) return null;

  const totalMarks = student.totalMarks ?? 25;
  const percentage = Math.round((totalMarks / student.maxMarks) * 100);

  const getGrade = (pct: number) => {
    if (pct >= 90) return 'A1';
    if (pct >= 80) return 'A2';
    if (pct >= 70) return 'B1';
    if (pct >= 60) return 'B2';
    if (pct >= 50) return 'C1';
    return 'D (Needs Support)';
  };

  const grade = getGrade(percentage);

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    const reportText = `
================================================================================
GREENWOOD PUBLIC SCHOOL — AFFILIATED TO CBSE, NEW DELHI
MID-TERM EXAMINATION 2026 · GRADE REPORT CARD
================================================================================
Student Name:   ${student.name}
Roll Number:    ${student.rollNo}
Class & Sec:    ${student.classSection}
Subject:        ${EXAM_META.subject}
Date Graded:    ${EXAM_META.gradedDate}
Overall Score:  ${totalMarks} / ${student.maxMarks} (${percentage}%)
Letter Grade:   ${grade}
Class Average:  ${EXAM_META.batchAverage} / 30

QUESTION-WISE SUMMARY:
${(student.questions || []).map((q) => `Q${q.qNum}: ${q.marksAwarded}/${q.maxMarks} Marks — ${q.feedback}`).join('\n')}

SUBJECT TEACHER REMARK (Ms. Anjali Rao):
"${percentage >= 80 ? 'Exceptional comprehension of scientific concepts and diagrammatic clarity.' : percentage >= 50 ? 'Satisfactory conceptual grasp. Focused revision recommended on descriptive question completeness.' : 'Needs focused attention and remedial concept practice on key NCERT chapters.'}"

================================================================================
Auto-generated by Copybook Examination Evaluation System
Parent Notification Dispatched via Email
================================================================================
`;
    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Report_Card_${student.name.replace(/\s+/g, '_')}_Class8A.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-xs flex items-center justify-center p-3 sm:p-6 print:p-0 print:bg-white">
      <div className="bg-[#121826] border border-[#25324c] rounded-2xl w-full max-w-3xl max-h-[92vh] flex flex-col overflow-hidden shadow-2xl print:bg-white print:border-none print:shadow-none print:text-black">
        {/* Top Control Bar */}
        <div className="px-6 py-4 border-b border-[#1f283d] flex items-center justify-between bg-[#151c2c] print:hidden">
          <div className="flex items-center gap-2.5">
            <Award className="w-5 h-5 text-blue-400" />
            <div>
              <h3 className="text-base font-bold text-white">
                Parent Report Card Preview
              </h3>
              <p className="text-xs text-slate-400">
                Official dispatch preview for parents of {student.name}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 text-xs font-semibold text-slate-300 bg-[#1e2a42] hover:bg-[#283857] hover:text-white rounded-lg border border-[#304163] transition-colors inline-flex items-center gap-1.5 cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>
            <button
              onClick={handleDownload}
              className="px-3 py-1.5 text-xs font-semibold text-white bg-blue-600 hover:bg-blue-500 rounded-lg transition-colors inline-flex items-center gap-1.5 cursor-pointer shadow-xs"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download Text</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-white rounded-lg hover:bg-[#1a2336] transition-colors ml-2 cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Certificate / Report Card Body */}
        <div className="p-6 sm:p-8 space-y-6 overflow-y-auto print:max-h-none print:overflow-visible bg-[#0f1422] text-slate-100 print:bg-white print:text-slate-900">
          {/* Header with school name */}
          <div className="text-center space-y-1.5 border-b border-[#222e47] pb-5 print:border-slate-300">
            <div className="text-[11px] font-mono tracking-widest uppercase text-blue-400 font-semibold print:text-slate-600">
              CBSE AFFILIATED INSTITUTION · NEW DELHI
            </div>
            <h2 className="font-serif text-2xl sm:text-3xl font-bold tracking-tight text-white print:text-slate-950">
              GREENWOOD PUBLIC SCHOOL
            </h2>
            <p className="text-xs text-slate-400 print:text-slate-600">
              Mid-Term Assessment Examination 2026–27 · Academic Performance Record
            </p>
          </div>

          {/* Student Meta Details */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-4 bg-[#162033] rounded-xl border border-[#23314d] text-xs print:bg-slate-50 print:border-slate-200 print:text-slate-800">
            <div>
              <span className="text-slate-400 block text-[11px] print:text-slate-500">Student Name</span>
              <span className="font-bold text-white text-sm print:text-slate-950">{student.name}</span>
            </div>
            <div>
              <span className="text-slate-400 block text-[11px] print:text-slate-500">Roll No &amp; Class</span>
              <span className="font-mono font-semibold text-slate-200 print:text-slate-900">Roll {student.rollNo} · {student.classSection}</span>
            </div>
            <div>
              <span className="text-slate-400 block text-[11px] print:text-slate-500">Subject</span>
              <span className="font-semibold text-slate-200 print:text-slate-900">{EXAM_META.subject}</span>
            </div>
            <div>
              <span className="text-slate-400 block text-[11px] print:text-slate-500">Evaluation Mode</span>
              <span className="font-semibold text-blue-300 print:text-slate-900">NCERT Rubric Graded</span>
            </div>
          </div>

          {/* Score & Grade Hero Summary */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-center">
            <div className="p-4 bg-[#182338] border border-[#2c3d5f] rounded-xl print:bg-slate-100 print:border-slate-300">
              <span className="text-xs text-slate-400 block print:text-slate-600">Total Marks Scored</span>
              <div className="text-3xl font-extrabold font-mono text-white mt-1 print:text-slate-950">
                {totalMarks} <span className="text-sm font-normal text-slate-400">/ {student.maxMarks}</span>
              </div>
            </div>

            <div className="p-4 bg-[#182338] border border-[#2c3d5f] rounded-xl print:bg-slate-100 print:border-slate-300">
              <span className="text-xs text-slate-400 block print:text-slate-600">Percentage</span>
              <div className="text-3xl font-extrabold font-mono text-blue-300 mt-1 print:text-blue-700">
                {percentage}%
              </div>
            </div>

            <div className="p-4 bg-[#182338] border border-[#2c3d5f] rounded-xl print:bg-slate-100 print:border-slate-300">
              <span className="text-xs text-slate-400 block print:text-slate-600">CBSE Letter Grade</span>
              <div className="text-3xl font-extrabold font-mono text-emerald-400 mt-1 print:text-emerald-700">
                {grade}
              </div>
            </div>
          </div>

          {/* Question Breakdown Table */}
          <div className="space-y-2">
            <div className="text-[11px] font-mono uppercase text-slate-400 tracking-wider">
              QUESTION-WISE SCORE BREAKDOWN
            </div>
            <div className="rounded-xl border border-[#222e47] overflow-hidden print:border-slate-300">
              <table className="w-full text-left text-xs border-collapse">
                <thead>
                  <tr className="bg-[#162033] border-b border-[#222e47] text-[11px] font-mono text-slate-400 uppercase print:bg-slate-100 print:text-slate-600">
                    <th className="py-2.5 px-3 w-10">Q#</th>
                    <th className="py-2.5 px-3">Topic / Concept</th>
                    <th className="py-2.5 px-3 w-24 text-center">Marks</th>
                    <th className="py-2.5 px-3">Teacher Assessment Feedback</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#1e273b] print:divide-slate-200">
                  {(student.questions || []).map((q) => {
                    const qMeta = PARSED_QUESTIONS.find((item) => item.qNum === q.qNum);
                    return (
                      <tr key={q.qNum} className="hover:bg-[#151c2c] print:hover:bg-transparent">
                        <td className="py-2 px-3 font-mono font-bold text-slate-300 print:text-slate-900">
                          {q.qNum}
                        </td>
                        <td className="py-2 px-3 text-slate-300 font-medium print:text-slate-800">
                          {qMeta?.topic}
                        </td>
                        <td className="py-2 px-3 text-center font-mono font-bold text-white print:text-slate-950">
                          {q.marksAwarded} / {q.maxMarks}
                        </td>
                        <td className="py-2 px-3 text-slate-400 text-[11px] print:text-slate-700">
                          {q.feedback}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>

          {/* Teacher Remark & Signatures */}
          <div className="pt-2 border-t border-[#222e47] space-y-4 print:border-slate-300">
            <div className="p-4 bg-[#141b2b] rounded-xl border border-[#23304a] text-xs space-y-1 print:bg-slate-50 print:border-slate-200">
              <span className="font-mono text-[11px] uppercase tracking-wider text-slate-400 block">
                Subject Teacher Remarks (Ms. Anjali Rao):
              </span>
              <p className="italic text-slate-200 font-serif print:text-slate-800 text-sm">
                &ldquo;{percentage >= 80 ? 'Exceptional comprehension of scientific concepts and diagrammatic clarity.' : percentage >= 50 ? 'Satisfactory conceptual grasp. Focused revision recommended on descriptive question completeness.' : 'Needs focused attention and remedial concept practice on key NCERT chapters.'}&rdquo;
              </p>
            </div>

            <div className="flex items-center justify-between pt-4 text-xs text-slate-400 print:text-slate-600">
              <div>
                <div className="font-serif italic font-bold text-slate-200 text-sm print:text-slate-900">Ms. Anjali Rao</div>
                <div className="text-[10px] font-mono">Senior Science Faculty</div>
              </div>

              <div className="text-center">
                <span className="inline-flex items-center gap-1 text-[11px] text-emerald-400 font-mono">
                  <CheckCircle2 className="w-3.5 h-3.5" /> Approved on Roster
                </span>
                <div className="text-[10px] font-mono">Greenwood Public School</div>
              </div>

              <div className="text-right">
                <div className="font-serif italic font-bold text-slate-200 text-sm print:text-slate-900">Dr. K. S. Raman</div>
                <div className="text-[10px] font-mono">Principal / Head of Institution</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
